#!perl -T
use 5.006;
use strict;
use warnings;
use Test::More;

use cshuji::Slurm qw(get_associations);

my $associations = "Cluster|Account|User|Partition|Share|GrpJobs|GrpTRES|GrpSubmit|GrpWall|GrpTRESMins|MaxJobs|MaxTRES|MaxTRESPerNode|MaxSubmit|MaxWall|MaxTRESMins|QOS|Def QOS|GrpTRESRunMins|
debug|root|||8||||||||||||high,low,normal,requeue|normal||
debug|default|||10|||||||||0|||high,low,normal,requeue|normal||
debug|default|lazarus||1||license/interactive=10|||||||0|||high,low,normal,requeue|normal||
debug|guests|||10||cpu=6,mem=9165M,gres/gpu=0||||||||||high,low,normal,requeue|normal||
debug|killable-debug|lazarus||1||license/interactive=10||||||||||killable-1|killable-1||
debug|owners|||10||||||||||||high,low,normal,requeue|normal||
debug|projects|||10||cpu=2,mem=1833M,gres/gpu=0||||||||||high,low,normal,requeue|normal||
debug|projects|lazarus||1||license/interactive=10||||||||||high,low,normal,requeue|normal||
rebug|root|||1||||||||||||high,low,normal,requeue|normal||
rebug|default|||1|||||||||0|||high,low,normal,requeue|normal||
rebug|guests|||1||cpu=9,mem=16827M,gres/gpu=1||||||||||high,low,normal,requeue|normal||
rebug|killable-debug|||1||||||||||||high,low,normal,requeue|normal||
rebug|owners|||1||||||||||||high,low,normal,requeue|normal||
rebug|irush|||1||cpu=8,mem=21019M,gres/gpu=2||||||||||high,low,normal,requeue|normal||
rebug|irush|lazarus||1||||||||||||high,low,normal,requeue|normal||
";

my @associations = (
                    {
                     "Cluster"           => "debug",
                     "Account"           => "root",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "8",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "default",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "10",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "0",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "default",
                     "User"              => "lazarus",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "license/interactive=10",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "0",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "guests",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "10",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "cpu=6,mem=9165M,gres/gpu=0",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "killable-debug",
                     "User"              => "lazarus",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "license/interactive=10",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "killable-1",
                     "Def QOS"           => "killable-1",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "owners",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "10",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "projects",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "10",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "cpu=2,mem=1833M,gres/gpu=0",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "debug",
                     "Account"           => "projects",
                     "User"              => "lazarus",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "license/interactive=10",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "root",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "default",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "0",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "guests",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "cpu=9,mem=16827M,gres/gpu=1",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "killable-debug",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "owners",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "irush",
                     "User"              => "",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "cpu=8,mem=21019M,gres/gpu=2",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                    {
                     "Cluster"           => "rebug",
                     "Account"           => "irush",
                     "User"              => "lazarus",
                     "Partition"         => "",
                     "Share"             => "1",
                     "GrpJobs"           => "",
                     "GrpTRES"           => "",
                     "GrpSubmit"         => "",
                     "GrpWall"           => "",
                     "GrpTRESMins"       => "",
                     "MaxJobs"           => "",
                     "MaxTRES"           => "",
                     "MaxTRESPerNode"    => "",
                     "MaxSubmit"         => "",
                     "MaxWall"           => "",
                     "MaxTRESMins"       => "",
                     "QOS"               => "high,low,normal,requeue",
                     "Def QOS"           => "normal",
                     "GrpTRESRunMins"    => "",
                    },
                   );


my $results = get_associations(_sacctmgr_output => [split /\n/, $associations]);
is_deeply($results, \@associations);

done_testing();
