#!perl
use 5.006;
use strict;
use warnings;
use Test::More;

use cshuji::Slurm qw(get_config);

my $config = "Configuration data as of 2019-03-05T16:41:12
AccountingStorageBackupHost = (null)
AccountingStorageEnforce = associations,limits,qos,safe
AccountingStorageHost   = slurm-db
AccountingStorageLoc    = N/A
AccountingStoragePort   = 6819
AccountingStorageTRES   = cpu,mem,energy,node,billing,gres/gpu,license/interactive
AccountingStorageType   = accounting_storage/slurmdbd
AccountingStorageUser   = N/A
AccountingStoreJobComment = Yes
AcctGatherEnergyType    = acct_gather_energy/none
AcctGatherFilesystemType = acct_gather_filesystem/none
AcctGatherInterconnectType = acct_gather_interconnect/none
AcctGatherNodeFreq      = 0 sec
AcctGatherProfileType   = acct_gather_profile/none
AllowSpecResourcesUsage = 0
AuthInfo                = (null)
AuthType                = auth/munge
BackupAddr              = sulfur-01
BackupController        = sulfur-01
BatchStartTimeout       = 20 sec
BOOT_TIME               = 2019-03-04T00:05:52
BurstBufferType         = (null)
CheckpointType          = checkpoint/none
ChosLoc                 = (null)
ClusterName             = phoenix
CompleteWait            = 0 sec
ControlAddr             = slurmctl-01
ControlMachine          = slurmctl-01
CoreSpecPlugin          = core_spec/none
CpuFreqDef              = Unknown
CpuFreqGovernors        = Performance,OnDemand
CryptoType              = crypto/munge
DebugFlags              = (null)
DefMemPerCPU            = 50
DisableRootJobs         = Yes
EioTimeout              = 60
EnforcePartLimits       = NO
Epilog                  = (null)
EpilogMsgTime           = 2000 usec
EpilogSlurmctld         = (null)
ExtSensorsType          = ext_sensors/none
ExtSensorsFreq          = 0 sec
FairShareDampeningFactor = 5
FastSchedule            = 0
FederationParameters    = (null)
FirstJobId              = 1
GetEnvTimeout           = 2 sec
GresTypes               = gpu
GroupUpdateForce        = 1
GroupUpdateTime         = 600 sec
HASH_VAL                = Match
HealthCheckInterval     = 10800 sec
HealthCheckNodeState    = CYCLE,ANY
HealthCheckProgram      = /cs/share/scripts/slurm.git/healthcheck.sh
InactiveLimit           = 0 sec
JobAcctGatherFrequency  = 30
JobAcctGatherType       = jobacct_gather/cgroup
JobAcctGatherParams     = (null)
JobCheckpointDir        = /var/slurm/checkpoint
JobCompHost             = localhost
JobCompLoc              = /var/log/slurm_jobcomp.log
JobCompPort             = 0
JobCompType             = jobcomp/none
JobCompUser             = root
JobContainerType        = job_container/none
JobCredentialPrivateKey = (null)
JobCredentialPublicCertificate = (null)
JobFileAppend           = 0
JobRequeue              = 0
JobSubmitPlugins        = job_submit/valid_partitions,job_submit/limit_interactive,job_submit/killable
KeepAliveTime           = SYSTEM_DEFAULT
KillOnBadExit           = 0
KillWait                = 30 sec
LaunchParameters        = (null)
LaunchType              = launch/slurm
Layouts                 = 
Licenses                = interactive:5000
LicensesUsed            = interactive:2/5000
LogTimeFormat           = iso8601_ms
MailDomain              = (null)
MailProg                = /vol/slurm/common/mail.sh
MaxArraySize            = 5001
MaxJobCount             = 50000
MaxJobId                = 67043328
MaxMemPerCPU            = 2097152
MaxStepCount            = 40000
MaxTasksPerNode         = 512
MCSPlugin               = mcs/none
MCSParameters           = (null)
MemLimitEnforce         = Yes
MessageTimeout          = 30 sec
MinJobAge               = 300 sec
MpiDefault              = none
MpiParams               = ports=12001-12999
MsgAggregationParams    = (null)
NEXT_JOB_ID             = 227123
NodeFeaturesPlugins     = (null)
OverTimeLimit           = 0 min
PluginDir               = /usr/local/slurm/17.11.12-1/lib/slurm
PlugStackConfig         = /cs/share/sysconf.git/slurm/phoenix/plugstack.conf
PowerParameters         = (null)
PowerPlugin             = 
PreemptMode             = REQUEUE
PreemptType             = preempt/qos
PriorityParameters      = (null)
PriorityDecayHalfLife   = 7-00:00:00
PriorityCalcPeriod      = 00:05:00
PriorityFavorSmall      = No
PriorityFlags           = 
PriorityMaxAge          = 7-00:00:00
PriorityUsageResetPeriod = NONE
PriorityType            = priority/multifactor
PriorityWeightAge       = 10000
PriorityWeightFairShare = 1000000
PriorityWeightJobSize   = 0
PriorityWeightPartition = 0
PriorityWeightQOS       = 10000000
PriorityWeightTRES      = (null)
PrivateData             = none
ProctrackType           = proctrack/cgroup
Prolog                  = (null)
PrologEpilogTimeout     = 65534
PrologSlurmctld         = (null)
PrologFlags             = (null)
PropagatePrioProcess    = 0
PropagateResourceLimits = (null)
PropagateResourceLimitsExcept = ALL
RebootProgram           = (null)
ReconfigFlags           = (null)
RequeueExit             = (null)
RequeueExitHold         = (null)
ResumeProgram           = (null)
ResumeRate              = 300 nodes/min
ResumeTimeout           = 60 sec
ResvEpilog              = (null)
ResvOverRun             = 0 min
ResvProlog              = (null)
ReturnToService         = 2
RoutePlugin             = route/default
SallocDefaultCommand    = (null)
SbcastParameters        = (null)
SchedulerParameters     = bf_window=30300
SchedulerTimeSlice      = 30 sec
SchedulerType           = sched/backfill
SelectType              = select/cons_res
SelectTypeParameters    = CR_CORE_MEMORY
SlurmUser               = slurm(147)
SlurmctldDebug          = debug
SlurmctldLogFile        = /var/log/slurmctld-phoenix.log
SlurmctldPort           = 6838
SlurmctldSyslogDebug    = info
SlurmctldTimeout        = 120 sec
SlurmdDebug             = info
SlurmdLogFile           = /vol/slurm/phoenix/logs/slurmd-\%h.log
SlurmdPidFile           = /var/run/slurmd-phoenix.pid
SlurmdPort              = 6818
SlurmdSpoolDir          = /var/spool/slurmd
SlurmdSyslogDebug       = info
SlurmdTimeout           = 300 sec
SlurmdUser              = root(0)
SlurmSchedLogFile       = (null)
SlurmSchedLogLevel      = 0
SlurmctldPidFile        = /var/run/slurmctld-phoenix.pid
SlurmctldPlugstack      = (null)
SLURM_CONF              = /vol/slurm/phoenix/slurm.conf
SLURM_VERSION           = 17.11.12
SrunEpilog              = (null)
SrunPortRange           = 0-0
SrunProlog              = (null)
StateSaveLocation       = /vol/slurm/phoenix/state
SuspendExcNodes         = (null)
SuspendExcParts         = (null)
SuspendProgram          = (null)
SuspendRate             = 60 nodes/min
SuspendTime             = NONE
SuspendTimeout          = 30 sec
SwitchType              = switch/none
TaskEpilog              = (null)
TaskPlugin              = task/cgroup
TaskPluginParam         = (null type)
TaskProlog              = /cs/share/scripts/slurm.git/proepilogs/TaskPrologs.sh
TCPTimeout              = 2 sec
TmpFS                   = /tmp
TopologyParam           = (null)
TopologyPlugin          = topology/none
TrackWCKey              = No
TreeWidth               = 50
UsePam                  = 1
UnkillableStepProgram   = /cs/share/scripts/slurm.git/unkillable-program.sh
UnkillableStepTimeout   = 300 sec
VSizeFactor             = 0 percent
WaitTime                = 0 sec

Slurmctld(primary/backup) at slurmctl-01/sulfur-01 are UP/UP
";

my %config = ("AccountingStorageBackupHost" => "(null)",
              "AccountingStorageEnforce" => "associations,limits,qos,safe",
              "AccountingStorageHost" => "slurm-db",
              "AccountingStorageLoc" => "N/A",
              "AccountingStoragePort" => "6819",
              "AccountingStorageTRES" => "cpu,mem,energy,node,billing,gres/gpu,license/interactive",
              "AccountingStorageType" => "accounting_storage/slurmdbd",
              "AccountingStorageUser" => "N/A",
              "AccountingStoreJobComment" => "Yes",
              "AcctGatherEnergyType" => "acct_gather_energy/none",
              "AcctGatherFilesystemType" => "acct_gather_filesystem/none",
              "AcctGatherInterconnectType" => "acct_gather_interconnect/none",
              "AcctGatherNodeFreq" => "0 sec",
              "AcctGatherProfileType" => "acct_gather_profile/none",
              "AllowSpecResourcesUsage" => "0",
              "AuthInfo" => "(null)",
              "AuthType" => "auth/munge",
              "BackupAddr" => "sulfur-01",
              "BackupController" => "sulfur-01",
              "BatchStartTimeout" => "20 sec",
              "BOOT_TIME" => "2019-03-04T00:05:52",
              "BurstBufferType" => "(null)",
              "CheckpointType" => "checkpoint/none",
              "ChosLoc" => "(null)",
              "ClusterName" => "phoenix",
              "CompleteWait" => "0 sec",
              "ControlAddr" => "slurmctl-01",
              "ControlMachine" => "slurmctl-01",
              "CoreSpecPlugin" => "core_spec/none",
              "CpuFreqDef" => "Unknown",
              "CpuFreqGovernors" => "Performance,OnDemand",
              "CryptoType" => "crypto/munge",
              "DebugFlags" => "(null)",
              "DefMemPerCPU" => "50",
              "DisableRootJobs" => "Yes",
              "EioTimeout" => "60",
              "EnforcePartLimits" => "NO",
              "Epilog" => "(null)",
              "EpilogMsgTime" => "2000 usec",
              "EpilogSlurmctld" => "(null)",
              "ExtSensorsType" => "ext_sensors/none",
              "ExtSensorsFreq" => "0 sec",
              "FairShareDampeningFactor" => "5",
              "FastSchedule" => "0",
              "FederationParameters" => "(null)",
              "FirstJobId" => "1",
              "GetEnvTimeout" => "2 sec",
              "GresTypes" => "gpu",
              "GroupUpdateForce" => "1",
              "GroupUpdateTime" => "600 sec",
              "HASH_VAL" => "Match",
              "HealthCheckInterval" => "10800 sec",
              "HealthCheckNodeState" => "CYCLE,ANY",
              "HealthCheckProgram" => "/cs/share/scripts/slurm.git/healthcheck.sh",
              "InactiveLimit" => "0 sec",
              "JobAcctGatherFrequency" => "30",
              "JobAcctGatherType" => "jobacct_gather/cgroup",
              "JobAcctGatherParams" => "(null)",
              "JobCheckpointDir" => "/var/slurm/checkpoint",
              "JobCompHost" => "localhost",
              "JobCompLoc" => "/var/log/slurm_jobcomp.log",
              "JobCompPort" => "0",
              "JobCompType" => "jobcomp/none",
              "JobCompUser" => "root",
              "JobContainerType" => "job_container/none",
              "JobCredentialPrivateKey" => "(null)",
              "JobCredentialPublicCertificate" => "(null)",
              "JobFileAppend" => "0",
              "JobRequeue" => "0",
              "JobSubmitPlugins" => "job_submit/valid_partitions,job_submit/limit_interactive,job_submit/killable",
              "KeepAliveTime" => "SYSTEM_DEFAULT",
              "KillOnBadExit" => "0",
              "KillWait" => "30 sec",
              "LaunchParameters" => "(null)",
              "LaunchType" => "launch/slurm",
              "Layouts" => "",
              "Licenses" => "interactive:5000",
              "LicensesUsed" => "interactive:2/5000",
              "LogTimeFormat" => "iso8601_ms",
              "MailDomain" => "(null)",
              "MailProg" => "/vol/slurm/common/mail.sh",
              "MaxArraySize" => "5001",
              "MaxJobCount" => "50000",
              "MaxJobId" => "67043328",
              "MaxMemPerCPU" => "2097152",
              "MaxStepCount" => "40000",
              "MaxTasksPerNode" => "512",
              "MCSPlugin" => "mcs/none",
              "MCSParameters" => "(null)",
              "MemLimitEnforce" => "Yes",
              "MessageTimeout" => "30 sec",
              "MinJobAge" => "300 sec",
              "MpiDefault" => "none",
              "MpiParams" => "ports=12001-12999",
              "MsgAggregationParams" => "(null)",
              "NEXT_JOB_ID" => "227123",
              "NodeFeaturesPlugins" => "(null)",
              "OverTimeLimit" => "0 min",
              "PluginDir" => "/usr/local/slurm/17.11.12-1/lib/slurm",
              "PlugStackConfig" => "/cs/share/sysconf.git/slurm/phoenix/plugstack.conf",
              "PowerParameters" => "(null)",
              "PowerPlugin" => "",
              "PreemptMode" => "REQUEUE",
              "PreemptType" => "preempt/qos",
              "PriorityParameters" => "(null)",
              "PriorityDecayHalfLife" => "7-00:00:00",
              "PriorityCalcPeriod" => "00:05:00",
              "PriorityFavorSmall" => "No",
              "PriorityFlags" => "",
              "PriorityMaxAge" => "7-00:00:00",
              "PriorityUsageResetPeriod" => "NONE",
              "PriorityType" => "priority/multifactor",
              "PriorityWeightAge" => "10000",
              "PriorityWeightFairShare" => "1000000",
              "PriorityWeightJobSize" => "0",
              "PriorityWeightPartition" => "0",
              "PriorityWeightQOS" => "10000000",
              "PriorityWeightTRES" => "(null)",
              "PrivateData" => "none",
              "ProctrackType" => "proctrack/cgroup",
              "Prolog" => "(null)",
              "PrologEpilogTimeout" => "65534",
              "PrologSlurmctld" => "(null)",
              "PrologFlags" => "(null)",
              "PropagatePrioProcess" => "0",
              "PropagateResourceLimits" => "(null)",
              "PropagateResourceLimitsExcept" => "ALL",
              "RebootProgram" => "(null)",
              "ReconfigFlags" => "(null)",
              "RequeueExit" => "(null)",
              "RequeueExitHold" => "(null)",
              "ResumeProgram" => "(null)",
              "ResumeRate" => "300 nodes/min",
              "ResumeTimeout" => "60 sec",
              "ResvEpilog" => "(null)",
              "ResvOverRun" => "0 min",
              "ResvProlog" => "(null)",
              "ReturnToService" => "2",
              "RoutePlugin" => "route/default",
              "SallocDefaultCommand" => "(null)",
              "SbcastParameters" => "(null)",
              "SchedulerParameters" => "bf_window=30300",
              "SchedulerTimeSlice" => "30 sec",
              "SchedulerType" => "sched/backfill",
              "SelectType" => "select/cons_res",
              "SelectTypeParameters" => "CR_CORE_MEMORY",
              "SlurmUser" => "slurm(147)",
              "SlurmctldDebug" => "debug",
              "SlurmctldLogFile" => "/var/log/slurmctld-phoenix.log",
              "SlurmctldPort" => "6838",
              "SlurmctldSyslogDebug" => "info",
              "SlurmctldTimeout" => "120 sec",
              "SlurmdDebug" => "info",
              "SlurmdLogFile" => "/vol/slurm/phoenix/logs/slurmd-\%h.log",
              "SlurmdPidFile" => "/var/run/slurmd-phoenix.pid",
              "SlurmdPort" => "6818",
              "SlurmdSpoolDir" => "/var/spool/slurmd",
              "SlurmdSyslogDebug" => "info",
              "SlurmdTimeout" => "300 sec",
              "SlurmdUser" => "root(0)",
              "SlurmSchedLogFile" => "(null)",
              "SlurmSchedLogLevel" => "0",
              "SlurmctldPidFile" => "/var/run/slurmctld-phoenix.pid",
              "SlurmctldPlugstack" => "(null)",
              "SLURM_CONF" => "/vol/slurm/phoenix/slurm.conf",
              "SLURM_VERSION" => "17.11.12",
              "SrunEpilog" => "(null)",
              "SrunPortRange" => "0-0",
              "SrunProlog" => "(null)",
              "StateSaveLocation" => "/vol/slurm/phoenix/state",
              "SuspendExcNodes" => "(null)",
              "SuspendExcParts" => "(null)",
              "SuspendProgram" => "(null)",
              "SuspendRate" => "60 nodes/min",
              "SuspendTime" => "NONE",
              "SuspendTimeout" => "30 sec",
              "SwitchType" => "switch/none",
              "TaskEpilog" => "(null)",
              "TaskPlugin" => "task/cgroup",
              "TaskPluginParam" => "(null type)",
              "TaskProlog" => "/cs/share/scripts/slurm.git/proepilogs/TaskPrologs.sh",
              "TCPTimeout" => "2 sec",
              "TmpFS" => "/tmp",
              "TopologyParam" => "(null)",
              "TopologyPlugin" => "topology/none",
              "TrackWCKey" => "No",
              "TreeWidth" => "50",
              "UsePam" => "1",
              "UnkillableStepProgram" => "/cs/share/scripts/slurm.git/unkillable-program.sh",
              "UnkillableStepTimeout" => "300 sec",
              "VSizeFactor" => "0 percent",
              "WaitTime" => "0 sec",
             );
my %cgroup;

my $config2 = "Configuration data as of 2019-09-11T14:07:04
AccountingStorageBackupHost = (null)
AccountingStorageEnforce = associations,limits,qos,safe
AccountingStorageHost   = slurmctl-02
AccountingStorageLoc    = N/A
AccountingStoragePort   = 6819
AccountingStorageTRES   = cpu,mem,energy,node,billing,fs/disk,vmem,pages,gres/gpu,license/interactive
AccountingStorageType   = accounting_storage/slurmdbd
AccountingStorageUser   = N/A
AccountingStoreJobComment = Yes
AcctGatherEnergyType    = acct_gather_energy/none
AcctGatherFilesystemType = acct_gather_filesystem/none
AcctGatherInterconnectType = acct_gather_interconnect/none
AcctGatherNodeFreq      = 0 sec
AcctGatherProfileType   = acct_gather_profile/none
AllowSpecResourcesUsage = 0
AuthAltTypes            = (null)
AuthInfo                = (null)
AuthType                = auth/munge
BatchStartTimeout       = 10 sec
BOOT_TIME               = 2019-09-10T18:09:50
BurstBufferType         = (null)
CheckpointType          = checkpoint/none
CliFilterPlugins        = (null)
ClusterName             = debug
CommunicationParameters = (null)
CompleteWait            = 0 sec
CoreSpecPlugin          = core_spec/none
CpuFreqDef              = Unknown
CpuFreqGovernors        = Performance,OnDemand,UserSpace
CredType                = cred/munge
DebugFlags              = (null)
DefMemPerCPU            = 50
DisableRootJobs         = Yes
EioTimeout              = 60
EnforcePartLimits       = NO
Epilog                  = (null)
EpilogMsgTime           = 2000 usec
EpilogSlurmctld         = /etc/slurm/epilog.sh
ExtSensorsType          = ext_sensors/none
ExtSensorsFreq          = 0 sec
FairShareDampeningFactor = 1
FastSchedule            = 0
FederationParameters    = (null)
FirstJobId              = 1
GetEnvTimeout           = 2 sec
GresTypes               = gpu,vmem
GpuFreqDef              = high,memory=high
GroupUpdateForce        = 1
GroupUpdateTime         = 600 sec
HASH_VAL                = Match
HealthCheckInterval     = 600 sec
HealthCheckNodeState    = CYCLE,ANY
HealthCheckProgram      = /cs/share/scripts/slurm.git/healthcheck.sh
InactiveLimit           = 0 sec
JobAcctGatherFrequency  = 30
JobAcctGatherType       = jobacct_gather/cgroup
JobAcctGatherParams     = (null)
JobCheckpointDir        = /var/slurm/checkpoint
JobCompHost             = localhost
JobCompLoc              = /var/log/slurm_jobcomp.log
JobCompPort             = 0
JobCompType             = jobcomp/none
JobCompUser             = root
JobContainerType        = job_container/none
JobCredentialPrivateKey = (null)
JobCredentialPublicCertificate = (null)
JobDefaults             = (null)
JobFileAppend           = 0
JobRequeue              = 0
JobSubmitPlugins        = job_submit/meta_partitions,job_submit/valid_partitions,job_submit/default_options,job_submit/limit_interactive,job_submit/killable
KeepAliveTime           = SYSTEM_DEFAULT
KillOnBadExit           = 0
KillWait                = 10 sec
LaunchParameters        = (null)
LaunchType              = launch/slurm
Layouts                 = 
Licenses                = interactive:1000
LicensesUsed            = interactive:0/1000
LogTimeFormat           = iso8601_ms
MailDomain              = (null)
MailProg                = /vol/slurm/common/mail.sh
MaxArraySize            = 1001
MaxJobCount             = 10000
MaxJobId                = 67043328
MaxMemPerCPU            = 2097152
MaxStepCount            = 40000
MaxTasksPerNode         = 512
MCSPlugin               = mcs/none
MCSParameters           = (null)
MessageTimeout          = 10 sec
MinJobAge               = 300 sec
MpiDefault              = none
MpiParams               = (null)
MsgAggregationParams    = (null)
NEXT_JOB_ID             = 134238106
NodeFeaturesPlugins     = (null)
OverTimeLimit           = 0 min
PluginDir               = /usr/local/slurm/19.05.1-2/lib/slurm
PlugStackConfig         = /vol/slurm/debug/plugstack.conf
PowerParameters         = (null)
PowerPlugin             = 
PreemptMode             = REQUEUE
PreemptType             = preempt/qos
PreemptExemptTime       = 00:00:00
PriorityParameters      = (null)
PrioritySiteFactorParameters = (null)
PrioritySiteFactorPlugin = (null)
PriorityDecayHalfLife   = 7-00:00:00
PriorityCalcPeriod      = 00:05:00
PriorityFavorSmall      = No
PriorityFlags           = 
PriorityMaxAge          = 7-00:00:00
PriorityUsageResetPeriod = NONE
PriorityType            = priority/multifactor
PriorityWeightAge       = 1000
PriorityWeightAssoc     = 0
PriorityWeightFairShare = 100000
PriorityWeightJobSize   = 0
PriorityWeightPartition = 0
PriorityWeightQOS       = 1000000
PriorityWeightTRES      = (null)
PrivateData             = none
ProctrackType           = proctrack/cgroup
Prolog                  = (null)
PrologEpilogTimeout     = 65534
PrologSlurmctld         = /etc/slurm/prolog-slurmctld.sh
PrologFlags             = (null)
PropagatePrioProcess    = 0
PropagateResourceLimits = (null)
PropagateResourceLimitsExcept = ALL
RebootProgram           = (null)
ReconfigFlags           = (null)
RequeueExit             = (null)
RequeueExitHold         = (null)
ResumeFailProgram       = (null)
ResumeProgram           = (null)
ResumeRate              = 300 nodes/min
ResumeTimeout           = 60 sec
ResvEpilog              = (null)
ResvOverRun             = 0 min
ResvProlog              = (null)
ReturnToService         = 2
RoutePlugin             = route/default
SallocDefaultCommand    = (null)
SbcastParameters        = (null)
SchedulerParameters     = bf_window=30300
SchedulerTimeSlice      = 30 sec
SchedulerType           = sched/backfill
SelectType              = select/cons_res
SelectTypeParameters    = CR_CORE_MEMORY
SlurmUser               = slurm(147)
SlurmctldAddr           = (null)
SlurmctldDebug          = debug5
SlurmctldHost[0]        = slurmctl-01
SlurmctldLogFile        = /var/log/slurmctld-debug.log
SlurmctldPort           = 6817
SlurmctldSyslogDebug    = debug
SlurmctldPrimaryOffProg = (null)
SlurmctldPrimaryOnProg  = (null)
SlurmctldTimeout        = 30 sec
SlurmctldParameters     = (null)
SlurmdDebug             = debug5
SlurmdLogFile           = /vol/slurm/debug/logs/slurmd-%h.log
SlurmdParameters        = (null)
SlurmdPidFile           = /var/run/slurmd-debug.pid
SlurmdPort              = 6818
SlurmdSpoolDir          = /var/spool/slurmd
SlurmdSyslogDebug       = info
SlurmdTimeout           = 300 sec
SlurmdUser              = root(0)
SlurmSchedLogFile       = (null)
SlurmSchedLogLevel      = 0
SlurmctldPidFile        = /var/run/slurmctld-debug.pid
SlurmctldPlugstack      = (null)
SLURM_CONF              = /vol/slurm/debug/slurm.conf
SLURM_VERSION           = 19.05.1-2
SrunEpilog              = (null)
SrunPortRange           = 0-0
SrunProlog              = (null)
StateSaveLocation       = /vol/slurm/debug/state
SuspendExcNodes         = (null)
SuspendExcParts         = (null)
SuspendProgram          = (null)
SuspendRate             = 60 nodes/min
SuspendTime             = NONE
SuspendTimeout          = 30 sec
SwitchType              = switch/none
TaskEpilog              = (null)
TaskPlugin              = task/cgroup
TaskPluginParam         = (null type)
TaskProlog              = /cs/share/scripts/slurm.git/proepilogs/TaskPrologs.sh
TCPTimeout              = 2 sec
TmpFS                   = /tmp
TopologyParam           = (null)
TopologyPlugin          = topology/none
TrackWCKey              = No
TreeWidth               = 50
UsePam                  = 1
UnkillableStepProgram   = /cs/share/scripts/slurm.git/unkillable-program.sh
UnkillableStepTimeout   = 10 sec
VSizeFactor             = 0 percent
WaitTime                = 0 sec
X11Parameters           = (null)

Cgroup Support Configuration:
AllowedDevicesFile      = /vol/slurm/debug/cgroup_allowed_devices_file.conf
AllowedKmemSpace        = (null)
AllowedRAMSpace         = 100.0%
AllowedSwapSpace        = 0.0%
CgroupAutomount         = no
CgroupMountpoint        = /sys/fs/cgroup
ConstrainCores          = yes
ConstrainDevices        = yes
ConstrainKmemSpace      = no
ConstrainRAMSpace       = yes
ConstrainSwapSpace      = yes
MaxKmemPercent          = 100.0%
MaxRAMPercent           = 100.0%
MaxSwapPercent          = 100.0%
MemorySwappiness        = (null)
MinKmemSpace            = 30 MB
MinRAMSpace             = 30 MB
TaskAffinity            = no

Slurmctld(primary) at slurmctl-01 is UP
";

my %config2 = ("AccountingStorageBackupHost" => "(null)",
               "AccountingStorageEnforce" => "associations,limits,qos,safe",
               "AccountingStorageHost" => "slurmctl-02",
               "AccountingStorageLoc" => "N/A",
               "AccountingStoragePort" => "6819",
               "AccountingStorageTRES" => "cpu,mem,energy,node,billing,fs/disk,vmem,pages,gres/gpu,license/interactive",
               "AccountingStorageType" => "accounting_storage/slurmdbd",
               "AccountingStorageUser" => "N/A",
               "AccountingStoreJobComment" => "Yes",
               "AcctGatherEnergyType" => "acct_gather_energy/none",
               "AcctGatherFilesystemType" => "acct_gather_filesystem/none",
               "AcctGatherInterconnectType" => "acct_gather_interconnect/none",
               "AcctGatherNodeFreq" => "0 sec",
               "AcctGatherProfileType" => "acct_gather_profile/none",
               "AllowSpecResourcesUsage" => "0",
               "AuthAltTypes" => "(null)",
               "AuthInfo" => "(null)",
               "AuthType" => "auth/munge",
               "BatchStartTimeout" => "10 sec",
               "BOOT_TIME" => "2019-09-10T18:09:50",
               "BurstBufferType" => "(null)",
               "CheckpointType" => "checkpoint/none",
               "CliFilterPlugins" => "(null)",
               "ClusterName" => "debug",
               "CommunicationParameters" => "(null)",
               "CompleteWait" => "0 sec",
               "CoreSpecPlugin" => "core_spec/none",
               "CpuFreqDef" => "Unknown",
               "CpuFreqGovernors" => "Performance,OnDemand,UserSpace",
               "CredType" => "cred/munge",
               "DebugFlags" => "(null)",
               "DefMemPerCPU" => "50",
               "DisableRootJobs" => "Yes",
               "EioTimeout" => "60",
               "EnforcePartLimits" => "NO",
               "Epilog" => "(null)",
               "EpilogMsgTime" => "2000 usec",
               "EpilogSlurmctld" => "/etc/slurm/epilog.sh",
               "ExtSensorsType" => "ext_sensors/none",
               "ExtSensorsFreq" => "0 sec",
               "FairShareDampeningFactor" => "1",
               "FastSchedule" => "0",
               "FederationParameters" => "(null)",
               "FirstJobId" => "1",
               "GetEnvTimeout" => "2 sec",
               "GresTypes" => "gpu,vmem",
               "GpuFreqDef" => "high,memory=high",
               "GroupUpdateForce" => "1",
               "GroupUpdateTime" => "600 sec",
               "HASH_VAL" => "Match",
               "HealthCheckInterval" => "600 sec",
               "HealthCheckNodeState" => "CYCLE,ANY",
               "HealthCheckProgram" => "/cs/share/scripts/slurm.git/healthcheck.sh",
               "InactiveLimit" => "0 sec",
               "JobAcctGatherFrequency" => "30",
               "JobAcctGatherType" => "jobacct_gather/cgroup",
               "JobAcctGatherParams" => "(null)",
               "JobCheckpointDir" => "/var/slurm/checkpoint",
               "JobCompHost" => "localhost",
               "JobCompLoc" => "/var/log/slurm_jobcomp.log",
               "JobCompPort" => "0",
               "JobCompType" => "jobcomp/none",
               "JobCompUser" => "root",
               "JobContainerType" => "job_container/none",
               "JobCredentialPrivateKey" => "(null)",
               "JobCredentialPublicCertificate" => "(null)",
               "JobDefaults" => "(null)",
               "JobFileAppend" => "0",
               "JobRequeue" => "0",
               "JobSubmitPlugins" => "job_submit/meta_partitions,job_submit/valid_partitions,job_submit/default_options,job_submit/limit_interactive,job_submit/killable",
               "KeepAliveTime" => "SYSTEM_DEFAULT",
               "KillOnBadExit" => "0",
               "KillWait" => "10 sec",
               "LaunchParameters" => "(null)",
               "LaunchType" => "launch/slurm",
               "Layouts" => "",
               "Licenses" => "interactive:1000",
               "LicensesUsed" => "interactive:0/1000",
               "LogTimeFormat" => "iso8601_ms",
               "MailDomain" => "(null)",
               "MailProg" => "/vol/slurm/common/mail.sh",
               "MaxArraySize" => "1001",
               "MaxJobCount" => "10000",
               "MaxJobId" => "67043328",
               "MaxMemPerCPU" => "2097152",
               "MaxStepCount" => "40000",
               "MaxTasksPerNode" => "512",
               "MCSPlugin" => "mcs/none",
               "MCSParameters" => "(null)",
               "MessageTimeout" => "10 sec",
               "MinJobAge" => "300 sec",
               "MpiDefault" => "none",
               "MpiParams" => "(null)",
               "MsgAggregationParams" => "(null)",
               "NEXT_JOB_ID" => "134238106",
               "NodeFeaturesPlugins" => "(null)",
               "OverTimeLimit" => "0 min",
               "PluginDir" => "/usr/local/slurm/19.05.1-2/lib/slurm",
               "PlugStackConfig" => "/vol/slurm/debug/plugstack.conf",
               "PowerParameters" => "(null)",
               "PowerPlugin" => "",
               "PreemptMode" => "REQUEUE",
               "PreemptType" => "preempt/qos",
               "PreemptExemptTime" => "00:00:00",
               "PriorityParameters" => "(null)",
               "PrioritySiteFactorParameters" => "(null)",
               "PrioritySiteFactorPlugin" => "(null)",
               "PriorityDecayHalfLife" => "7-00:00:00",
               "PriorityCalcPeriod" => "00:05:00",
               "PriorityFavorSmall" => "No",
               "PriorityFlags" => "",
               "PriorityMaxAge" => "7-00:00:00",
               "PriorityUsageResetPeriod" => "NONE",
               "PriorityType" => "priority/multifactor",
               "PriorityWeightAge" => "1000",
               "PriorityWeightAssoc" => "0",
               "PriorityWeightFairShare" => "100000",
               "PriorityWeightJobSize" => "0",
               "PriorityWeightPartition" => "0",
               "PriorityWeightQOS" => "1000000",
               "PriorityWeightTRES" => "(null)",
               "PrivateData" => "none",
               "ProctrackType" => "proctrack/cgroup",
               "Prolog" => "(null)",
               "PrologEpilogTimeout" => "65534",
               "PrologSlurmctld" => "/etc/slurm/prolog-slurmctld.sh",
               "PrologFlags" => "(null)",
               "PropagatePrioProcess" => "0",
               "PropagateResourceLimits" => "(null)",
               "PropagateResourceLimitsExcept" => "ALL",
               "RebootProgram" => "(null)",
               "ReconfigFlags" => "(null)",
               "RequeueExit" => "(null)",
               "RequeueExitHold" => "(null)",
               "ResumeFailProgram" => "(null)",
               "ResumeProgram" => "(null)",
               "ResumeRate" => "300 nodes/min",
               "ResumeTimeout" => "60 sec",
               "ResvEpilog" => "(null)",
               "ResvOverRun" => "0 min",
               "ResvProlog" => "(null)",
               "ReturnToService" => "2",
               "RoutePlugin" => "route/default",
               "SallocDefaultCommand" => "(null)",
               "SbcastParameters" => "(null)",
               "SchedulerParameters" => "bf_window=30300",
               "SchedulerTimeSlice" => "30 sec",
               "SchedulerType" => "sched/backfill",
               "SelectType" => "select/cons_res",
               "SelectTypeParameters" => "CR_CORE_MEMORY",
               "SlurmUser" => "slurm(147)",
               "SlurmctldAddr" => "(null)",
               "SlurmctldDebug" => "debug5",
               "SlurmctldHost[0]" => "slurmctl-01",
               "SlurmctldLogFile" => "/var/log/slurmctld-debug.log",
               "SlurmctldPort" => "6817",
               "SlurmctldSyslogDebug" => "debug",
               "SlurmctldPrimaryOffProg" => "(null)",
               "SlurmctldPrimaryOnProg" => "(null)",
               "SlurmctldTimeout" => "30 sec",
               "SlurmctldParameters" => "(null)",
               "SlurmdDebug" => "debug5",
               "SlurmdLogFile" => "/vol/slurm/debug/logs/slurmd-%h.log",
               "SlurmdParameters" => "(null)",
               "SlurmdPidFile" => "/var/run/slurmd-debug.pid",
               "SlurmdPort" => "6818",
               "SlurmdSpoolDir" => "/var/spool/slurmd",
               "SlurmdSyslogDebug" => "info",
               "SlurmdTimeout" => "300 sec",
               "SlurmdUser" => "root(0)",
               "SlurmSchedLogFile" => "(null)",
               "SlurmSchedLogLevel" => "0",
               "SlurmctldPidFile" => "/var/run/slurmctld-debug.pid",
               "SlurmctldPlugstack" => "(null)",
               "SLURM_CONF" => "/vol/slurm/debug/slurm.conf",
               "SLURM_VERSION" => "19.05.1-2",
               "SrunEpilog" => "(null)",
               "SrunPortRange" => "0-0",
               "SrunProlog" => "(null)",
               "StateSaveLocation" => "/vol/slurm/debug/state",
               "SuspendExcNodes" => "(null)",
               "SuspendExcParts" => "(null)",
               "SuspendProgram" => "(null)",
               "SuspendRate" => "60 nodes/min",
               "SuspendTime" => "NONE",
               "SuspendTimeout" => "30 sec",
               "SwitchType" => "switch/none",
               "TaskEpilog" => "(null)",
               "TaskPlugin" => "task/cgroup",
               "TaskPluginParam" => "(null type)",
               "TaskProlog" => "/cs/share/scripts/slurm.git/proepilogs/TaskPrologs.sh",
               "TCPTimeout" => "2 sec",
               "TmpFS" => "/tmp",
               "TopologyParam" => "(null)",
               "TopologyPlugin" => "topology/none",
               "TrackWCKey" => "No",
               "TreeWidth" => "50",
               "UsePam" => "1",
               "UnkillableStepProgram" => "/cs/share/scripts/slurm.git/unkillable-program.sh",
               "UnkillableStepTimeout" => "10 sec",
               "VSizeFactor" => "0 percent",
               "WaitTime" => "0 sec",
               "X11Parameters" => "(null)",
               "_CgroupSupportConfiguration" => {"AllowedDevicesFile" => "/vol/slurm/debug/cgroup_allowed_devices_file.conf",
                                                 "AllowedKmemSpace" => "(null)",
                                                 "AllowedRAMSpace" => "100.0%",
                                                 "AllowedSwapSpace" => "0.0%",
                                                 "CgroupAutomount" => "no",
                                                 "CgroupMountpoint" => "/sys/fs/cgroup",
                                                 "ConstrainCores" => "yes",
                                                 "ConstrainDevices" => "yes",
                                                 "ConstrainKmemSpace" => "no",
                                                 "ConstrainRAMSpace" => "yes",
                                                 "ConstrainSwapSpace" => "yes",
                                                 "MaxKmemPercent" => "100.0%",
                                                 "MaxRAMPercent" => "100.0%",
                                                 "MaxSwapPercent" => "100.0%",
                                                 "MemorySwappiness" => "(null)",
                                                 "MinKmemSpace" => "30 MB",
                                                 "MinRAMSpace" => "30 MB",
                                                 "TaskAffinity" => "no",
                                                },
              );

my $errors = [];
my $results = get_config(_scontrol_output => [split /\n/, $config], errors => $errors);

is_deeply($results, \%config);
ok(@$errors == 0, "Too many errors: ".scalar(@$errors)." (structured input)");

$errors = [];
$results = get_config(_scontrol_output => [split /\n/, $config2], errors => $errors);

is_deeply($results, \%config2);
ok(@$errors == 0, "Too many errors: ".scalar(@$errors)." (structured input)");

$results = get_config(errors => $errors);
ok(@$errors == 0, "Too many errors: ".scalar(@$errors)." (scontrol show config)");
ok(ref $results eq "HASH", $errors->[0]);

done_testing();
