#!perl -T
use 5.006;
use strict;
use warnings;
use Test::More;

use cshuji::Slurm qw(get_accounts);

my $accounts = "Account|Descr|Org|Cluster|Par Name|User|Share|GrpJobs|GrpNodes|GrpCPUs|GrpMem|GrpSubmit|GrpWall|GrpCPUMins|MaxJobs|MaxNodes|MaxCPUs|MaxSubmit|MaxWall|MaxCPUMins|QOS|Def QOS|GrpTRES|
default|default|default|debug|root||10|||||||||||0|||high,low,normal,requeue|normal||
default|default|default|debug||lazarus|1|||||||||||0|||high,low,normal,requeue|normal|license/interactive=10|
default|default|default|rebug|root||1|||||||||||0|||high,low,normal,requeue|normal||
guests|guests|guests|debug|root||10|||6|9165||||||||||high,low,normal,requeue|normal|cpu=6,mem=9165M,gres/gpu=0|
guests|guests|guests|rebug|root||1|||9|16827||||||||||high,low,normal,requeue|normal|cpu=9,mem=16827M,gres/gpu=1|
root|default root account|root|debug|||8||||||||||||||high,low,normal,requeue|normal||
root|default root account|root|rebug|||1||||||||||||||high,low,normal,requeue|normal||
guest1|lms: |guests|phoenix|guests||1|||473|3042837||||||||||high,killable-1,low,normal,requeue|normal|cpu=473,mem=3042837M,gres/gpu=29|
guest1|lms: |guests|phoenix||user1|1||||||||||||||high,killable-1,low,normal,requeue|normal|license/interactive=2|
";

my @accounts = ({
                 "Account"     => "default",
                 "Descr"       => "default",
                 "Org"         => "default",
                 "Cluster"     => "debug",
                 "Par Name"    => "root",
                 "User"        => "",
                 "Share"       => "10",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "",
                 "GrpMem"      => "",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "0",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "",
                },
                {
                 "Account"     => "default",
                 "Descr"       => "default",
                 "Org"         => "default",
                 "Cluster"     => "rebug",
                 "Par Name"    => "root",
                 "User"        => "",
                 "Share"       => "1",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "",
                 "GrpMem"      => "",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "0",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "",
                },
                {
                 "Account"     => "guests",
                 "Descr"       => "guests",
                 "Org"         => "guests",
                 "Cluster"     => "debug",
                 "Par Name"    => "root",
                 "User"        => "",
                 "Share"       => "10",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "6",
                 "GrpMem"      => "9165",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "cpu=6,mem=9165M,gres/gpu=0",
                },
                {
                 "Account"     => "guests",
                 "Descr"       => "guests",
                 "Org"         => "guests",
                 "Cluster"     => "rebug",
                 "Par Name"    => "root",
                 "User"        => "",
                 "Share"       => "1",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "9",
                 "GrpMem"      => "16827",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "cpu=9,mem=16827M,gres/gpu=1",
                },
                {
                 "Account"     => "root",
                 "Descr"       => "default root account",
                 "Org"         => "root",
                 "Cluster"     => "debug",
                 "Par Name"    => "",
                 "User"        => "",
                 "Share"       => "8",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "",
                 "GrpMem"      => "",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "",
                },
                {
                 "Account"     => "root",
                 "Descr"       => "default root account",
                 "Org"         => "root",
                 "Cluster"     => "rebug",
                 "Par Name"    => "",
                 "User"        => "",
                 "Share"       => "1",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "",
                 "GrpMem"      => "",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "",
                },
                {
                 "Account"     => "guest1",
                 "Descr"       => "lms: ",
                 "Org"         => "guests",
                 "Cluster"     => "phoenix",
                 "Par Name"    => "guests",
                 "User"        => "",
                 "Share"       => "1",
                 "GrpJobs"     => "",
                 "GrpNodes"    => "",
                 "GrpCPUs"     => "473",
                 "GrpMem"      => "3042837",
                 "GrpSubmit"   => "",
                 "GrpWall"     => "",
                 "GrpCPUMins"  => "",
                 "MaxJobs"     => "",
                 "MaxNodes"    => "",
                 "MaxCPUs"     => "",
                 "MaxSubmit"   => "",
                 "MaxWall"     => "",
                 "MaxCPUMins"  => "",
                 "QOS"         => "high,killable-1,low,normal,requeue",
                 "Def QOS"     => "normal",
                 "GrpTRES"     => "cpu=473,mem=3042837M,gres/gpu=29",
                },
               );


my $results = get_accounts(_sacctmgr_output => [split /\n/, $accounts]);
is_deeply($results, \@accounts);

done_testing();
